run_name: WikiMEL
seed: 43
pretrained_model: '/checkpoint/clip-vit-base-patch32'
lr: 5e-6


data:
  num_entity: 109976
  kb_img_folder: /data/WikiMEL/kb_image
  mention_img_folder: /data/WikiMEL/mention_image
  qid2id: /data/WikiMEL/qid2id.json
  entity: /data/WikiMEL/kb_entity.json
  train_file: /data/WikiMEL/WIKIMEL_train.json
  dev_file: /data/WikiMEL/WIKIMEL_dev.json
  test_file: /data/WikiMEL/WIKIMEL_test.json

  batch_size: 32
  num_workers: 8
  text_max_length: 50
  visual_patch_length: 50

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96
  num_experts: 4
  top_experts: 3


trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30